syntax = "proto3";

package librarian;

option go_package = "recon_com.lib.v1;lib";

service Librarian {
  // Получить список регионов
  rpc GetAllRegions(GetAllRegionsRequest) returns (GetAllRegionsResponse); //TODO починить

  // Получить ссылку для скачивания файла
  rpc GetURLForDownloadSource(GetURLForDownloadSourceRequest) returns (GetURLForDownloadSourceResponse);

  // Получить список источников по фильтру
  // rpc GetSourcesByFilter(GetSourcesByFilterRequest) returns (GetSourcesByFilterResponse) //TODO отложено

  // Передать информацию для сохранения источника
  rpc UploadSourceDataForDownload(UploadSourceDataForDownloadRequest) returns (UploadSourceDataForDownloadResponse);
}

/////////////////////////////////////////////////////////////////

// Передать информацию для сохранения источника
message UploadSourceDataForDownloadRequest {
  int64 userID = 1;
  SourceType source_type = 2;
  string name_ru = 3;
  string name_eng = 4;
  string author_ru = 5;
  int64 year = 6;
  string description = 7;
  string download_url = 8;
  string created_at = 9;
}

message UploadSourceDataForDownloadResponse {
  int64 id = 1;
  bool is_saved = 2;
}

//// Получить список источников по фильтру //TODO отложено
//message GetSourcesByFilterRequest {
//    SourceFilter source_filter = 1;
//    uint32 limit = 2;
//    uint32 offset = 3;
//}
//
//message SourceFilter { //TODO отложено
//  repeated int32 ids = 1;
//  repeated int32 object_ids = 2;
//  repeated SourceType type = 3;
//  // Временные периоды
//  // Регионы
//  // Объекты реконструкции
//}
//
//message GetSourcesByFilterResponse { //TODO отложено
//
//}
//
//message Source { //TODO отложено
//  int32 id = 1;
//  int32 object_id = 2;
//  string address = 3;
//  google.protobuf.Timestamp created_at = 4;
//  SourceType type = 5;
//  string time_periods = 6;
//}

// Тип источника
enum SourceType {
  SOURCE_TYPE_UNKNOWN = 0;
  SOURCE_TYPE_BOOK = 1;
  SOURCE_TYPE_ARTICLE = 2;
  SOURCE_TYPE_FRAGMENT = 3;
  SOURCE_TYPE_PHOTO = 4;
}

// Получить ссылку для скачивания файла
message GetURLForDownloadSourceRequest{
  int64 source_id = 1;
}

message GetURLForDownloadSourceResponse{
  string URLForDownload = 1;
  FileInfo file_info = 2;
}

message FileInfo{
  int64 size = 1;
  string file_name = 2;
  string file_type = 3;
}

// Получить список регионов
message GetAllRegionsRequest{}

message GetAllRegionsResponse{
  repeated Region region = 1;
}

message Region {
  int64 id = 1;
  string name_ru = 2;
  string description = 3;
}
